# Generated by Django 6.1.1 on 2026-09-23 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('context', models.TextField(blank=True)),
                ('need', models.TextField(blank=True)),
                ('users', models.TextField(blank=True)),
                ('data_and_materials', models.TextField(blank=True)),
                ('constraints', models.TextField(blank=True)),
                ('expected_result', models.TextField(blank=True)),
                ('success_criteria', models.TextField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('collaboration_format', models.TextField(blank=True)),
                ('readiness_score', models.PositiveSmallIntegerField(default=0)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('interests', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('technologies', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.TextField()),
                ('plan', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('prototype_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='tasks_app.task')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='tasks_app.team')),
            ],
        ),
    ]
